### Send a query to create a Jira story
POST http://127.0.0.1:5000/query-my-data
Content-Type: application/json

{
    "question": "How do I create a Jira story with the summary 'Test' and the description 'Test' using the Jira API?"
}

### Send a query to add a comment to a specific Jira story
POST http://127.0.0.1:5000/query-my-data
Content-Type: application/json

{
    "question": "How do add the comment 'Better living through chemistry' to the Jira story with Key 'TEST-1' using the Jira API?"
}
